version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_QUEUE_NAME=text_generation
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=DEBUG
      - BATCH_WINDOW_MS=250
      - MAX_REQUESTS_PER_JOB=4
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - app-network
    restart: unless-stopped
    tty: true
    stdin_open: true

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: rq worker text_generation --url redis://redis:6379
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_QUEUE_NAME=text_generation
      - LOG_LEVEL=DEBUG
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: 