version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_QUEUE_NAME=${REDIS_QUEUE_NAME}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - BATCH_WINDOW_MS=${BATCH_WINDOW_MS}
      - MAX_REQUESTS_PER_JOB=${MAX_REQUESTS_PER_JOB}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - app-network
    restart: unless-stopped
    tty: true
    stdin_open: true

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: rq worker ${REDIS_QUEUE_NAME} --url ${REDIS_URL}
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_QUEUE_NAME=${REDIS_QUEUE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      replicas: 1  # Here we can scale workers

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: 